### ISSUE TITLE
dialer scramble

### ISSUE THREAD

**Issue by nerfiaux** [CODeRUS/sailfishos-scramble-lockpad-patch#1]
in my case, i have installed the patch to have dialer by default when i open the phone app.
my experience is that the phone dialer is scrambled which is not necessary.
the sim pin code request is not scrambled : ok
the security pin at start and unlock is scrambled : ok
phone dialer is scrambled : ko
thanks.

**Comment by CODeRUS** [comment]
Fixed in v0.0.2
https://github.com/CODeRUS/sailfishos-scramble-lockpad-patch/commit/4688904d52c55f4b11db94fcfacbc38822b41f33
