### ISSUE TITLE
Blue Key in the scrambled pad : Correct code not accepted

### ISSUE THREAD

**Issue by nerfiaux** [CODeRUS/sailfishos-scramble-lockpad-patch#2]
Hi Andrey,

Sometimes when i wake up the phone, 
i have in the scrambled pad a blue key.
When I type the correct code it is not accepted.
I have to do it again.
This issue may be in state To Be Confirmed.

Thx, great work.

**Comment by CODeRUS** [comment]
You should at leat photo your screen and show it

**Comment by nerfiaux** [comment]
Hi Andrey,
Issue Closed !
I removed the patch to prepare the next Jolla update 11th.
And yesterday It happen to me again.
So it is a native sailfishOS issue.
So I will take a look on the Jolla2gether, if it exist, or I will open this subject.
